files:
  - source: '*.md'
    ignore:
      - /*.md
    translation: '%original_path%/%original_file_name%'
  - source: '*.yml'
    ignore:
      - .github/
    translation: '%original_path%/%original_file_name%'
